export const AUTH_ATTEMPTING = 'AUTH_ATTEMTING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const LOGGED_OUT = 'LOGGED_OUT';
export const GET_PROFILE = 'GET_PROFILE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const DELETE_MOE = 'DELETE_MOE';
export const UPDATE_MOE = 'UPDATE_MOE';
export const RESET = 'RESET';

export const GET_ALL_MOE_SUCCESS = 'GET_ALL_MOE_SUCESS';
export const GET_ALL_MOE_FAILED = 'GET_ALL_MOE_FAILED';
export const GET_ALL_MOE_ATTEMPTING = 'GET_ALL_MOE_ATTEMPTING';

export const GET_ALL_PRODUITS_SUCCESS = 'GET_ALL_PRODUITS_SUCESS';
export const GET_ALL_PRODUITS_FAILED = 'GET_ALL_PRODUITS_FAILED';
export const GET_ALL_PRODUITS_ATTEMPTING = 'GET_ALL_PRODUITS_ATTEMPTING';

export const GET_ALL_SERVICES_SUCCESS = 'GET_ALL_SERVICES_SUCESS';
export const GET_ALL_SERVICES_FAILED = 'GET_ALL_SERVICES_FAILED';
export const GET_ALL_SERVICES_ATTEMPTING = 'GET_ALL_SERVICESS_ATTEMPTING';

export const ADD_ERROR = 'ADD_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


