/* Auth */ 
export const AUTH_ATTEMPTING = 'AUTH_ATTEMTING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const LOGGED_OUT = 'LOGGED_OUT';
export const GET_PROFILE = 'GET_PROFILE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const DELETE_MOE = 'DELETE_MOE';
export const UPDATE_MOE = 'UPDATE_MOE';
export const RESET = 'RESET';

/* All Moes */ 
export const GET_ALL_MOE_SUCCESS = 'GET_ALL_MOE_SUCESS';
export const GET_ALL_MOE_FAILED = 'GET_ALL_MOE_FAILED';
export const GET_ALL_MOE_ATTEMPTING = 'GET_ALL_MOE_ATTEMPTING';

/* All Produits */ 
export const GET_ALL_PRODUITS_SUCCESS = 'GET_ALL_PRODUITS_SUCESS';
export const GET_ALL_PRODUITS_FAILED = 'GET_ALL_PRODUITS_FAILED';
export const GET_ALL_PRODUITS_ATTEMPTING = 'GET_ALL_PRODUITS_ATTEMPTING';

/* All Moe Produits */ 
export const ADD_PRODUIT = 'ADD_PRODUIT';
export const GET_MOE_PRODUIT_SUCCESS = 'GET_MOE_PRODUIT_SUCCESS';
export const GET_MOE_PRODUIT_FAILED = 'GET_MOE_PRODUIT_FAILED';
export const GETTING_MOE_PRODUIT = 'GETTING_MOE';
export const DELETE_PRODUIT = 'DELETE_PRODUIT';
export const UPDATE_PRODUIT = 'UPDATE_PRODUIT';
export const CLEAR_PRODUIT = 'CLEAR_PRODUIT'; 

/* All Moe Services */ 
export const ADD_SERVICE = 'ADD_SERVICE';
export const GET_MOE_SERVICE_SUCCESS = 'GET_MOE_SERVICE_SUCCESS';
export const GET_MOE_SERVICE_FAILED = 'GET_MOE_SERVICE_FAILED';
export const GETTING_MOE_SERVICE = 'GETTING_MOE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const CLEAR_SERVICE = 'CLEAR_SERVICE'; 

/* All Services */
export const GET_ALL_SERVICES_SUCCESS = 'GET_ALL_SERVICES_SUCESS';
export const GET_ALL_SERVICES_FAILED = 'GET_ALL_SERVICES_FAILED';
export const GET_ALL_SERVICES_ATTEMPTING = 'GET_ALL_SERVICESS_ATTEMPTING';

/* Errors */
export const ADD_ERROR = 'ADD_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


